import { user } from "./types";
import default_img from "../../public/default_user_imgjpg.jpg";
import nftImg1 from "../../public/bitcoin_img.png";
import nftImg2 from "../../public/etherum-img.png";
import nftImg3 from "../../public/solana-img.png";

export const mockUsers: user[] = [
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 20,
    city: "New York",
    country: "USA",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas sed tempus urna et pharetra pharetra massa massa ultricies mi quis",
    name: "Jasmin",
    sex: "male",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 18,
    city: "Berlin",
    country: "Germany",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl eget duis at tellus at urna condimentum mattis pellentesque ",
    name: "Haler",
    sex: "female",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 30,
    city: "Warsaw",
    country: "Poland",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas sed tempus urna et pharetra pharetra massa massa ultricies mi quis",
    name: "Andrzej",
    sex: "male",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 48,
    city: "London",
    country: "England",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas sed tempus urna et pharetra pharetra massa massa ultricies mi quis",
    name: "Bob",
    sex: "male",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 21,
    city: "Paris",
    country: "France",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas sed tempus urna et pharetra pharetra massa massa ultricies mi quis",
    name: "Maclere",
    sex: "female",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 21,
    city: "Quebec",
    country: "Canada",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas sed tempus urna et pharetra pharetra massa massa ultricies mi quis",
    name: "Felix",
    sex: "male",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 21,
    city: "Rome",
    country: "Italy",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas sed tempus urna et pharetra pharetra massa massa ultricies mi quis",
    name: "Lugo",
    sex: "male",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
  {
    profilePic: default_img,
    "favNFT1-contractAddress": "contract1",
    "favNFT1-tokenID": "id1",
    "favNFT2-contractAddress": "contract2",
    "favNFT2-tokenID": "id2",
    "favNFT3-contractAddress": "contract3",
    "favNFT3-tokenID": "id3",
    age: 21,
    city: "Barcelona",
    country: "Spain",
    description:
      "semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas sed tempus urna et pharetra pharetra massa massa ultricies mi quis",
    name: "Camilla",
    sex: "female",
    nft1Img: nftImg1,
    nft2Img: nftImg2,
    nft3Img: nftImg3,
  },
];
